import React, { createContext, useState } from "react";
import type { Rental } from "../types/rental";

interface RentalContextType {
  rentals: Rental[];
  addRental: (rental: Rental) => void;
  updateRental: (id: string, updates: Partial<Rental>) => void;
  deleteRental: (id: string) => void;
}

export const RentalContext = createContext<RentalContextType | undefined>(undefined);

export const RentalProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [rentals, setRentals] = useState<Rental[]>([
    {
      id: "1",
      title: "Apartamento Centro - Airbnb",
      address: "Rua das Flores, 123 - Centro, São Paulo, SP",
      description: "Apartamento bem localizado, próximo ao metrô e comércio. Ideal para turistas e viajantes a negócio.",
      bedrooms: 2,
      bathrooms: 1,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 150,
      amenities: ["Wi-Fi", "Ar condicionado", "Cozinha equipada", "TV", "Estacionamento"],
      maxGuests: 4,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      instantBooking: true,
      cleaningFee: 50,
      serviceFee: 25,
    },
    {
      id: "2",
      title: "Casa na Praia - Booking",
      address: "Av. Beira Mar, 456 - Copacabana, Rio de Janeiro, RJ",
      description: "Casa com vista para o mar, a 2 quadras da praia. Ideal para famílias e grupos de amigos.",
      bedrooms: 3,
      bathrooms: 2,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 280,
      amenities: ["Wi-Fi", "Ar condicionado", "Cozinha completa", "Churrasqueira", "Piscina", "Vista para o mar"],
      maxGuests: 6,
      checkInTime: "15:00",
      checkOutTime: "10:00",
      instantBooking: false,
      cleaningFee: 80,
      serviceFee: 40,
    },
    {
      id: "3",
      title: "Loft Moderno - Airbnb",
      address: "Rua Augusta, 789 - Consolação, São Paulo, SP",
      description: "Loft moderno e elegante no coração de São Paulo. Perfeito para casais ou viajantes a negócio.",
      bedrooms: 1,
      bathrooms: 1,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 200,
      amenities: ["Wi-Fi", "Ar condicionado", "Cozinha americana", "Smart TV", "Academia"],
      maxGuests: 2,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      instantBooking: true,
      cleaningFee: 60,
      serviceFee: 30,
    },
    {
      id: "4",
      title: "Casa de Campo - Booking",
      address: "Estrada do Vinho, 321 - Bento Gonçalves, RS",
      description: "Casa rústica em meio às vinhas. Experiência única no interior do Rio Grande do Sul.",
      bedrooms: 2,
      bathrooms: 1,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 180,
      amenities: ["Wi-Fi", "Lareira", "Cozinha rústica", "Vista para vinhas", "Degustação de vinhos"],
      maxGuests: 4,
      checkInTime: "16:00",
      checkOutTime: "12:00",
      instantBooking: false,
      cleaningFee: 70,
      serviceFee: 35,
    },
    {
      id: "5",
      title: "Apartamento Luxo - Airbnb",
      address: "Av. Paulista, 1000 - Bela Vista, São Paulo, SP",
      description: "Apartamento de luxo com vista panorâmica da cidade. Mobiliário de alto padrão.",
      bedrooms: 2,
      bathrooms: 2,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 350,
      amenities: ["Wi-Fi", "Ar condicionado", "Cozinha gourmet", "Smart TV", "Academia", "Piscina", "Concierge"],
      maxGuests: 4,
      checkInTime: "15:00",
      checkOutTime: "11:00",
      instantBooking: true,
      cleaningFee: 100,
      serviceFee: 50,
    },
    {
      id: "6",
      title: "Casa na Montanha - Booking",
      address: "Rua das Pedras, 555 - Petrópolis, RJ",
      description: "Casa aconchegante na serra, com clima ameno e natureza exuberante.",
      bedrooms: 3,
      bathrooms: 2,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 220,
      amenities: ["Wi-Fi", "Lareira", "Cozinha completa", "Churrasqueira", "Vista para montanhas", "Trilhas"],
      maxGuests: 6,
      checkInTime: "14:00",
      checkOutTime: "12:00",
      instantBooking: false,
      cleaningFee: 90,
      serviceFee: 45,
    },
    {
      id: "7",
      title: "Studio Compacto - Airbnb",
      address: "Rua 7 de Setembro, 123 - Centro, Porto Alegre, RS",
      description: "Studio compacto e funcional, ideal para estadias curtas no centro da cidade.",
      bedrooms: 1,
      bathrooms: 1,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 120,
      amenities: ["Wi-Fi", "Ar condicionado", "Cozinha compacta", "TV", "Localização central"],
      maxGuests: 2,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      instantBooking: true,
      cleaningFee: 40,
      serviceFee: 20,
    },
    {
      id: "8",
      title: "Casa na Praia - Airbnb",
      address: "Rua do Coco, 789 - Praia do Forte, BA",
      description: "Casa rústica a 100m da praia, com vista para o mar e clima tropical.",
      bedrooms: 2,
      bathrooms: 1,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 250,
      amenities: ["Wi-Fi", "Ventilador", "Cozinha rústica", "Varanda", "Vista para o mar", "Proximidade da praia"],
      maxGuests: 4,
      checkInTime: "15:00",
      checkOutTime: "10:00",
      instantBooking: false,
      cleaningFee: 80,
      serviceFee: 40,
    },
    {
      id: "9",
      title: "Loft Industrial - Booking",
      address: "Rua da Indústria, 456 - Vila Madalena, São Paulo, SP",
      description: "Loft com decoração industrial, localizado no coração da Vila Madalena.",
      bedrooms: 1,
      bathrooms: 1,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 180,
      amenities: ["Wi-Fi", "Ar condicionado", "Cozinha americana", "Smart TV", "Decoração industrial", "Vida noturna"],
      maxGuests: 2,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      instantBooking: true,
      cleaningFee: 55,
      serviceFee: 28,
    },
    {
      id: "10",
      title: "Casa Colonial - Airbnb",
      address: "Rua do Ouro, 321 - Centro Histórico, Ouro Preto, MG",
      description: "Casa colonial restaurada no centro histórico, com toda a charmosa arquitetura mineira.",
      bedrooms: 2,
      bathrooms: 1,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 160,
      amenities: ["Wi-Fi", "Aquecimento", "Cozinha tradicional", "Vista histórica", "Café da manhã"],
      maxGuests: 4,
      checkInTime: "15:00",
      checkOutTime: "12:00",
      instantBooking: false,
      cleaningFee: 65,
      serviceFee: 32,
    },
    {
      id: "11",
      title: "Apartamento Executivo - Booking",
      address: "Av. Rio Branco, 100 - Centro, Rio de Janeiro, RJ",
      description: "Apartamento execututivo com vista para a Baía de Guanabara, ideal para viagens a negócio.",
      bedrooms: 1,
      bathrooms: 1,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 300,
      amenities: ["Wi-Fi", "Ar condicionado", "Cozinha equipada", "Smart TV", "Vista para baía", "Localização executiva"],
      maxGuests: 2,
      checkInTime: "14:00",
      checkOutTime: "11:00",
      instantBooking: true,
      cleaningFee: 75,
      serviceFee: 38,
    },
    {
      id: "12",
      title: "Casa na Serra - Airbnb",
      address: "Estrada da Serra, 555 - Serra da Mantiqueira, SP",
      description: "Casa de campo com vista panorâmica da serra, clima ameno e natureza preservada.",
      bedrooms: 3,
      bathrooms: 2,
      monthlyRent: 0,
      deposit: 0,
      businessType: "daily_rent",
      status: "active",
      dailyRate: 320,
      amenities: ["Wi-Fi", "Lareira", "Cozinha completa", "Churrasqueira", "Vista panorâmica", "Trilhas", "Cachoeiras"],
      maxGuests: 8,
      checkInTime: "16:00",
      checkOutTime: "12:00",
      instantBooking: false,
      cleaningFee: 120,
      serviceFee: 60,
    }
  ]);

  const addRental = (rental: Rental) => {
    setRentals(prev => [...prev, rental]);
  };

  const updateRental = (id: string, updates: Partial<Rental>) => {
    setRentals(prev => prev.map(rental =>
      rental.id === id ? { ...rental, ...updates } : rental
    ));
  };

  const deleteRental = (id: string) => {
    setRentals(prev => prev.filter(rental => rental.id !== id));
  };

  return (
    <RentalContext.Provider value={{ rentals, addRental, updateRental, deleteRental }}>
      {children}
    </RentalContext.Provider>
  );
}; 